import { ProfileView } from '@/app/[username]/profile-view'

// Demo data for showcasing the public profile
const demoProfile = {
    id: 'demo',
    username: 'dripqueen',
    display_name: 'Sophia Chen',
    bio: '💧 NYC Fashion Obsessed | Sharing my latest drops',
    avatar_url: null,
    theme: 'dark',
    created_at: new Date().toISOString(),
}

const demoItems = [
    {
        id: '1',
        user_id: 'demo',
        title: 'Zara Oversized Wool Blazer',
        brand: 'Zara',
        price: 149.00,
        currency: 'USD',
        image_url: null,
        link_url: 'https://zara.com',
        category: 'Outerwear',
        position: 0,
        is_active: true,
        clicks: 234,
        created_at: new Date().toISOString(),
    },
    {
        id: '2',
        user_id: 'demo',
        title: 'Nike Air Max 90 - Barely Rose',
        brand: 'Nike',
        price: 130.00,
        currency: 'USD',
        image_url: null,
        link_url: 'https://nike.com',
        category: 'Shoes',
        position: 1,
        is_active: true,
        clicks: 189,
        created_at: new Date().toISOString(),
    },
    {
        id: '3',
        user_id: 'demo',
        title: 'Levi\'s 501 Original Fit Jeans',
        brand: "Levi's",
        price: 98.00,
        currency: 'USD',
        image_url: null,
        link_url: 'https://levis.com',
        category: 'Bottoms',
        position: 2,
        is_active: true,
        clicks: 156,
        created_at: new Date().toISOString(),
    },
    {
        id: '4',
        user_id: 'demo',
        title: 'Mejuri Croissant Dome Earrings',
        brand: 'Mejuri',
        price: 78.00,
        currency: 'USD',
        image_url: null,
        link_url: 'https://mejuri.com',
        category: 'Accessories',
        position: 3,
        is_active: true,
        clicks: 98,
        created_at: new Date().toISOString(),
    },
    {
        id: '5',
        user_id: 'demo',
        title: 'COS Relaxed Cashmere Sweater',
        brand: 'COS',
        price: 225.00,
        currency: 'USD',
        image_url: null,
        link_url: 'https://cos.com',
        category: 'Tops',
        position: 4,
        is_active: true,
        clicks: 67,
        created_at: new Date().toISOString(),
    },
]

export default function DemoPage() {
    return <ProfileView profile={demoProfile} items={demoItems} />
}
